version: "3"

services:
  backend:
    build: .
    image: hit_circle_server
    ports:
      - "8080:8080"
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: "backend-service"
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql:/var/lib/mysql